---
- name: Install "Monit"
  apt:
    name: monit
    state: present
    update_cache: true
  tags: monit

- name: Copy monit-config
  template:
    src: templates/monit-config.j2
    dest: /etc/monit/monitrc
  notify: Reload Monit
  tags: monit

- name: Copy monit-nginx-config
  template:
    src: templates/monit-nginx-config.j2
    dest: /etc/monit/conf-available/nginx
  notify: Reload Monit
  tags: monit
